---
title: "Dashboard"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    css: ./assets/css/style.css
    orientation: rows
    vertical_layout: fill
    social: menu
    number_sections: true
    theme: spacelab
---


```{r setup, include=FALSE}
###http://www.rapidtables.com/convert/energy/joule-to-kcal.htm
source("server/server_head.R")

#define verbose mode
verbose <- T

#define log file
flog.appender(appender.tee('message.log'))
flog.info("Start")

#define global variables
sizeDb <- 0
frequency <- 0
startTime <- 0
stopTime <- 0
deltaT <- 0


data <- data.frame()
dataCorrect <- data.frame()


# Define the list of available databases
lookupDb <- structure(c("server/databases/dbWalkMB61Hz.db", "server/databases/db50SquatsMPh16Hz.db","server/databases/dbEating.db", "server/databases/db50SquatsMB(61Hz).db","server/databases/dbEatingFatherMB(61Hz).db","server/databases/dbWalkMB-MPh.db", "server/databases/GrishaGoRunMB.db"), 
                  .Names = c("Walk-MB(61Hz)", "Squats50-MPh(16Hz)", "Eat-Mb(61Hz)", "Squats50-MB(61Hz)", "Eat-Father-Mb(61Hz)","WalkMB-MPh(GPS)", "GrishaGoRunMB"))

nameDb <- reactive( as.character(input$database))

dbCurrent <- 0

namePf <- reactive( as.character(input$platforme_type))

nameDs <- reactive( as.character(input$datasource))


# get input parameters for calcul integral 1
i1Axis <- reactive(as.character(input$i1Axis))
i1Min <- reactive(input$i1Min)
i1Max <- reactive(input$i1Max)
i1Filter <- reactive(input$i1Filter)
i1SigCentred <- reactive(input$i1SigCentred)
#i1SigLinear <- reactive(input$i1SigLinear)

#get input parameters for calcul integral 2
i2Axis <- reactive(as.character(input$i2Axis))
i2Min <- reactive(input$i2Min)
i2Max <- reactive(input$i2Max)
i2Filter <- reactive(input$i2Filter)
i2SigCentred <- reactive(input$i2SigCentred)
#i2SigLinear <- reactive(input$i2SigLinear)
i2Int1Centred <- reactive(input$i2Int1Centred)

#get input parameters for breakouts
brMin <- reactive(input$brMin)
brMax <- reactive(input$brMax)

#get input analysis parameters
alsAxis <- reactive(as.character(input$alsAxis))
alsMin <- reactive(input$alsMin)
alsMax <- reactive(input$alsMax)
alsCorrect <- reactive(input$alsCorrect)
alsFilters <-  reactive(input$asFilters) #as.character(input$asFilters))
alsSigCentred <- reactive(input$alsSigCentred)
#alsSigLinear <- reactive(input$alsSigLinear)

#get function for calcul
nameFunc <- reactive(as.character(input$functions))
#Event on Run button -> to execute function
resFunc <- eventReactive(input$funcRun ,{    
  switch(nameFunc(),
    "Integral1" = {if (verbose) flog.info("Event Integral 1"); func <- doIntegral1(); 
    ret <-(list("func"=func(), "plot"= plotIntegral( func(),input$spanLow)))},
    "Integral2" = {if (verbose) flog.info("Event Integral 2"); func <- doIntegral2(); 
    ret <-(list("func"=func(), "plot"= plotIntegral( func(),input$spanLow))) },
    "Breakouts" = {if (verbose) flog.info("Event Breakouts"); func <- doBreakouts();
    counter <- c(1:length(func()$loc)); x<- func()$loc 
    dev <- data.frame(counter, x)
    ret <-(list("func"=func(),  "plot"=plotBreakout(dev, "Breakouts")))},
    "Analysis" = { if (verbose) flog.info("Event Analysis"); func <- doAnalysis();
    #counter <- func()$peak;
    #x<- func()$sample;
    #data_t<-deleteBias_x(data())
  #  x <- fftfilt(rep(1, 10)/10, data_t$x)
    counter <- c(1:length( func() ) )
    x <- func()
    dev <- data.frame( counter, x )
  
  
    ret<-(list("func"=func(),"plot"= plotBreakout(dev,"Peaks")))}#plot.new()) )} 
  )
  return (ret) 
})


```



Sidebar {.sidebar}
======================================================================


```{r}

# Define input database
selectInput('database', label = h5('Select a database'), choices = lookupDb, selected = "dbEating.db")

# Define input platforme type
selectInput('platforme_type', label = h5('Select a platforme type'), choices = lookupPf, selected = "")


#sliderInput('span', label = 'Low Cutoff Fragment', min = 0.1, max = 0.9, #value = 0.3, step = 0.1)


connection <- reactive(openDatabase(nameDb()))

data <- reactive(selectData(connection(), nameDs(), namePf()))

sizeDb <- reactive(nrow(data()))
```

Found records = `r reactive(sizeDb())`

Frequency = `r reactive(frequency())`

Start time of recording = `r reactive(as.character(startTime()))`

Stop time of recording = `r reactive(as.character(stopTime()))`

Signal
================================================================================================



Row
---------------------------

```{r }

#Movement {data-navmenu="Signal"}
#======================================================================
#selectInput('datasource', label = h5('Select a signal type'), choices = lookupDsMove, selected = "Accelerometer")

selectInput('datasource', label = h6('Select a signal type'), choices = lookupDs, selected = "Accelerometer", width=145)
selectInput('functions', label = h6('Select a function'), choices = lookupFunc, selected = "", width=145)
```


### 
   

<div id="settings" style="display:none">

```{r }

conditionalPanel(
  condition = "input.functions == 'Integral1'",
  textInput( 'i1Min', label="min", value = 1 ),
  textInput( 'i1Max', label="max", value = 1 ),
  checkboxInput( 'i1Filter', label = 'Allow axis correction', value=T ),
  checkboxInput(' i1SigCentred', label = 'Allow signal centred', value=T ),        
  selectInput( 'i1Axis', label = 'Select a axis', choices = lookupAxis, selected = "X", width=100)
)
conditionalPanel(
  condition = "input.functions == 'Integral2'",
  textInput( 'i2Min', label="min", value = 1 ),
  textInput( 'i2Max', label="max", value = 1 ),
  checkboxInput( 'i2Filter', label = 'Allow axis correction', value=T ),
  checkboxInput( 'i2SigCentred', label = 'Allow signal centred', value=T ),        
  checkboxInput( 'i2Int1Centred', label = 'Allow integral1 centred', value=T ),
  selectInput( 'i2Axis', label = 'Select a axis', choices = lookupAxis, selected = "X", width=100 )
)
conditionalPanel(
  condition = "input.functions == 'Breakouts'",
  textInput( 'brMin', label="min", value = 1 ),
  textInput( 'brMax', label="max", value = 1 )
 # actionButton("funcRunBreakouts", "Run")
#  selectInput('anomaly_method', label = 'Select a mentod for anomaly detection', choices = lookup)
)
conditionalPanel(
  condition = "input.functions == 'Analysis'",
  selectInput( 'alsAxis', label = 'Select a axis', choices = lookupAxis, selected = "X", width=100 ),
#  textInput( 'alsMin', label="min", value = 1 ),
#  textInput( 'alsMax', label="max", value = 1 ),
  checkboxInput('alsCorrect', label = 'Allow axis correction', value=T ),
#  selectInput('alsFilters', label = 'Select a filter', choices = lookupFilters, selected = "FFT", width=100),
  checkboxInput( 'alsFilters', label = 'Allow filter FFT', value=F ), 
  checkboxInput( 'alsSigCentred', label = 'Allow signal centred', value=T )        
)
actionButton("funcRun", "Run")



```
</div>

 <button title="Click to show answer"  type="button" onclick="if(document.getElementById('settings') .style.display=='none') {document.getElementById('settings') .style.display=''}else{document.getElementById('settings') .style.display='none'}">Functions settings +/-</button>
   

 



Row  {data-height=1100 .tabset }
------------------------------------------------------------------------

### Signal  


```{r }

selectData <- function(con, ds, pf){

  switch(ds,
         "'ACCELEROMETER'" = selectMovementData(con, ds, pf),
         "'GYROSCOPE'" = selectMovementData(con, ds, pf),
          "'HEART_RATE'" = selectHealthData(con, ds, pf),
         "'SKIN_TEMPERATURE'" = selectHealthData(con, ds, pf),
         "'GALVANIC_SKIN_RESPONSE'" = selectHealthData(con, ds, pf),
         "'SPEED'" = selectHealthData(con, ds, pf),
         "'STEP_COUNT'" = selectHealthData(con, ds, pf),
         "'CALORY_BURN'" = selectHealthData(con, ds, pf),
         "'DISTANCE'" = selectHealthData(con, ds, pf),
         "'PACE'" = selectHealthData(con, ds, pf),         
         "'MOTION_TYPE'" = selectHealthData(con, ds, pf), 
         "'RR_INTERVAL'" = selectHealthData(con, ds, pf))
} 



plotData <- function(ds, data){

  switch(ds,
        "'ACCELEROMETER'" = plotMovementData(data, "Accelerometer"),
         "'GYROSCOPE'" = plotMovementData(data, "Gyroscope"),
         "'HEART_RATE'" = plotHealthData(data, "Heart rate"),
         "'SKIN_TEMPERATURE'" = plotHealthData(data, "Skin Temperature"),
         "'GALVANIC_SKIN_RESPONSE'" = plotHealthData(data, "Galvanic skin temperature"),
         "'SPEED'" = plotHealthData(data, "Speed"),
         "'STEP_COUNT'" = plotHealthData(data, "Step count"),
         "'CALORY_BURN'" = plotHealthData(data, "Calory burn"),
         "'DISTANCE'" = plotHealthData(data, "Distance"),
         "'PACE'" = plotHealthData(data, "Pace"),         
         "'MOTION_TYPE'" = plotHealthData(data, ""),
         "'RR_INTERVAL'" = plotHealthData(data, "RR interval")) 
}
comuteSizeDb <- function(data){
    return(length(data))
}  


output$scatterM <- renderDygraph({ plotData(nameDs(), data())})
dygraphOutput('scatterM', width = "80%")


minTime <-reactive(data()[1,]$dt)
maxTime <- reactive(data()[sizeDb(),]$dt)

startTime <- reactive(minTime())
stopTime <- reactive(maxTime())

deltaT <- reactive((as.numeric(maxTime()) - as.numeric(minTime()))/sizeDb())

frequency <- reactive(1/deltaT())
 
    
```

### Table
```{r}
#library(DT)
# renderDataTable({ 
#  DT::datatable(data()) %>% formatStyle(
 #   'x',
#    backgroundColor = styleInterval(3.4, c('gray', 'yellow'))
#  )
#})



renderPrint({
    summary(data())
  })


```


Row {data-height=1100 .tabset }
---------------------------------------------------------

### Signal
 

```{r}

selectFragment <- function( sig, a, b ){
  x <- sig$x[c( a:b )]
  y <- sig$y[c( a:b )]
  z <- sig$z[c( a:b )]
  counter <- c( a:b )
  fragment <- data.frame(counter, x, y , z)
  
  return( fragment )
}

getSubsetAxis <- function( sig, axis ){
  switch( axis,
         "X" = { subset <- sig$x } ,
         "Y" = { subset <- sig$y } ,
         "Z" = { subset <- sig$z } )
  return( subset )    
}

setSubsetAxis <- function( sig, subset, axis ){
    newSig <- data.frame()
    counter <- sig$counter
    switch( axis,
         "X" = { x <- subset; y <- sig$y; z <- sig$z  } ,
         "Y" = { y <- subset; x <- sig$x; z <- sig$z } ,
         "Z" = { z <- subset; y <- sig$y; x <- sig$x } )
  return( newSig <- data.frame( counter, x, y, z ) ) 
}

doCentred <- function( sigAxis, allowed ){
  if ( allowed == T ){ 
      meanValueAxis <- mean( sigAxis )
      centredAxis <- sigAxis - meanValueAxis
      return( centredAxis )
  }else { return( sigAxis ) }
}

doCorrect <- function( sig, axis, allowed   ){
  if ( allowed == T){
      switch( axis,
         "X" = { sigCorrect <- correctionX( sig ) } , 
         "Y" = { sigCorrect <- correctionY( sig ) } , 
         "Z" = { sigCorrect <- correctionZ( sig ) } 
      ) 
      return( sigCorrect )     
  }else { return( sig) }
}


```

```{r}
doIntegral1 <- function(){ 
  frgmnt <- reactive( selectFragment( data(), i1Min(), i1Max() ) )
  frgmntCor <- reactive( doCorrect( frgmnt(), i1Axis(), i1Filter() ) ) 
  axisSubset <- reactive( getSubsetAxis( frgmntCor(), i1Axis() ) )
  axisCentred <- reactive( doCentred( axisSubset(), i1SigCentred() ) )

  return( reactive( integral1( axisCentred(), 0, length( axisCentred() ), deltaT() ) ) )  
}
```

```{r}

doIntegral2 <- function(){
  frgmnt <- reactive( selectFragment( data(), i2Min(), i2Max() ) )
  frgmntCor <- reactive( doCorrect( frgmnt(), i2Axis(), i2Filter() ) ) 
  axisSubset <- reactive( getSubsetAxis( frgmntCor(), i2Axis() ) )
  axisCentred <- reactive( doCentred( axisSubset(), i2SigCentred() ) )

  return( reactive( integral2( axisCentred(), 0, length( axisCentred() ), deltaT(), i2Int1Centred() ) ) )  
}
```

```{r}
  doAnalysis <- function(){
   frgmntCor <- reactive( doCorrect( data(), alsAxis(), alsCorrect() ) )  
   axisSubset <- reactive( getSubsetAxis( frgmntCor(), alsAxis() ) )
   axisCentred <- reactive( doCentred( axisSubset(), alsSigCentred() ) )
  # alsData <- reactive( setSubsetAxis( data(), axisCentred(), alsAxis() ) )
   # pks <-reactive( as.data.frame(findUpPeaks(data()$x, 10)))
   return( reactive( axisCentred() ) ) # alsData() ) ) 
  #  return( reactive(pks()))
  }
```

```{r}
doBreakouts <- function(sig){

# data <- reactive(selectData(connection(), nameDs(), namePf()))
# reactive(breakout(data()$x, min.size=10, method='multi', beta=.001, degree=1,
 #               plot=TRUE))
 # output$breakout <- renderDygraph({breakout()$plot})
 

 #plotBreakout(breakout(), funcAxis())})
#dygraphOutput('breakout')
 return (  reactive(breakout(data()$x, min.size=10, method='multi', beta=.001, degree=1,
                plot=TRUE)))
 
}
```


```{r}
  doDensity <- function(sig){
    
  }
```




```{r}
  doMovement <- function(sig){
  #  data <- reactive(selectData(connection(), nameDs(), namePf()))
    #find peaks for all data`
    pks <-reactive( as.data.frame(findUpPeaks(data()$x, 10)))
    
  }

 
```

```{r}


  #renderPrint({(resFunc()$func)})
  output$integral <- renderDygraph({resFunc()$plot})
  dygraphOutput('integral')



#library(signal)
#reactive({
#cutoffHz <- 1.28
#sampleHz <- reactive(frequency())
#nyqHz = sampleHz()/2
#f <- butter(9, cutoffHz/nyqHz, type="low" )
#ts[,c('ly2') := lapply(.(y2), function(x)(filtfilt(f,intgrl())))]
#intgrl()$y2 <-ts$y2 - ts$ly2
#})
#intgrl()$y2 <- b})
```





```{r}
#data <- reactive(selectData(connection(), nameDs(), namePf()))
#breakout <- reactive(breakout(data()$x, 
#               min.size=10, method='multi', beta=.001, degree=1, plot=TRUE))

#reactive(bo$plot)
#output$breakout <- renderDygraph({breakout()$plot})
 

 #plotBreakout(breakout(), funcAxis())})
#dygraphOutput('breakout')
#data <- reactive(selectData(connection(), nameDs(), namePf()))

#output$density <- renderPlotly({ plotDensity(data(), funcAxis())}) 
#plotlyOutput('density', width = "40%")

#output$density <- renderDygraph({ plotDensity(data(), funcAxis())})
#dygraphOutput('Density', width = "40%", height = "30%")


```

### Data
```{r}
 # renderPrint(resFunc()$func)
```


### Summary
```{r}

renderPrint({
    summary(resFunc()$func)
})


```

Test
======================================================================

```{r}
lookupUci <- structure(c("server/databases/accelHar/11.csv","server/databases/accelHar/13.csv"
#"server/databases/uciHar/body_acc_x_train.txt", #"server/databases/uciHar/body_acc_y_train.txt","server/databases/uciHar/body_acc_z_train.txt","s#erver/databases/uciHar/body_gyro_x_train.txt","server/databases/uciHar/body_gyro_y_train.txt","s#erver/databases/uciHar/body_gyro_z_train.txt", "server/databases/uciHar/total_acc_x_train.txt", #"server/databases/uciHar/total_acc_y_train.txt", "server/databases/uciHar/total_acc_z_train.txt" 
), 
                  .Names = c("acc_sub_11","acc_sub_13"
#,"acc_x_filtered", "acc_y_filtered", "acc_z_filtered", "gyro_x", "gyro_y","gyro_z", "acc_x", #"acc_y", "acc_z"
))

selectInput('uciHarBase', label = h5('Select a database'), choices = lookupUci, selected = "acc_sub_11")
db <- reactive(input$uciHarBase)
#uci_db <- reactive(read.table(db()))
# read test database

t_db <- data.table()

tmp <- reactive(data.table(read.csv(db())))


digit <- reactive(gregexpr("[0-9]+", db()))
i<- reactive(as.numeric(unique(unlist(regmatches(db(), digit())))))
tmp1<- reactive((tmp()[, `:=`(id, factor(i()))]))
#test_db<-reactive(rbindlist(list(t_db, tmp1()), use.names = F))
output$test_db <-renderTable({
    test_db<-rbindlist(list(t_db, tmp1()), use.names = F)
    colnames(test_db)<-c( "nseq", "ax", "ay", "az", "action", "id")
  })                
# rename columns
#print(reactive(test_db()))
#names(reactive(test_db()) )<- c("nseq", "ax", "ay", "az", "action", "id")
#reactive(setnames(test_db(), c( "nseq", "ax", "ay", "az", "action", "id")))



```

###

```{r}
renderPrint('test_db')
#x <- reactive(as.vector(t(uci_db())))
#counter <- reactive(test_db)
#uci <- reactive(data.frame(counter(), x()))


#output$uci <- renderDygraph(plotMovementData(uci(), "Test"))
#dygraphOutput('uci')
```


Map
======================================================================



```{r}
# Draw the map without selected tracts
#output$map <- renderLeaflet({

#   data <-  merge(walking$ANDGPSLA, walking$ANDGPSLO, by=c("Date","Timestamp"))
#                data <-  merge(data, walking$ANDGPSSP, by=c("Date","Timestamp"))
#                colors <- heat.colors(7)[floor(data$ANDGPSSP) + 1]
#                colors <- substr(colors, 1, 7)
#                colors[is.na(colors)] <- "#aaaaaa"
#               map <- leaflet() %>%
#                addTiles() %>%  
#                addCircleMarkers(data=data.frame(lat=data$ANDGPSLA, lng=data$ANDGPSLO), 
#                                         radius=2, weight=0, fillColor=colors, fillOpacity=0.5)

#    map

 # })
#leafletOutput('map')  
```

```{r}
  # calories last 14 days
#library(ggvis)
#library(dplyr)
#library(shinydashboard)
#dtCalory <- reactive(selectHealthData(connection(), "'CALORY_BURN'" ,"'MICROSOFT_BAND'" ))
#dtSteps <- reactive(selectHealthData(connection(), "'STEP_COUNT'" ,"'MICROSOFT_BAND'" ))

  #  filter(dtCalory$counter > max(date) - 14) %>%
  #  filter(!is.na(dtSteps()$x)) %>%
 
#output$ggvis <- reactive({dtSteps()  %>%
##    ggvis(x=~counter,y= ~x) %>%
#    layer_lines() %>%
#   layer_points() %>%
#    add_axis("x", title="Date") %>%
#    add_axis("y", title="Calories Burned")%>%
#    set_options(width = "auto", height = 300)%>%
#    bind_shiny("ggvis","ggvis_ui")})

 #   ggvisOutput("ggvis")


```




Results
======================================================================


Row
-----------------------------------------------------------------------

```{r}

```


### Calories

```{r}

#calories <- computeCalories()
dtCalory <- reactive(selectHealthData(connection(), "'CALORY_BURN'" ,"'MICROSOFT_BAND'" ))

  minCl <- reactive(min(dtCalory()$x))
  maxCl <- reactive(max(dtCalory()$x))
  calories <- reactive(maxCl()-minCl())

renderValueBox({
        valueBox(
          value = tags$p(style = "font-size: 30px;",calories()),
           "Calories", icon = "fa-fire"
        )
      })

```


### Heart Rate

```{r}
dtHr <- reactive(selectHealthData(connection(), "'HEART_RATE'" ,"'MICROSOFT_BAND'" ))

 hr <- reactive(mean(dtHr()$x))

renderValueBox({
        valueBox(
          value = tags$p(style = "font-size: 30px;",(formatC(hr(),digits=3))),
           "Heart rate", icon = "fa-heartbeat"
     #   color = ifelse(hr > 170, "warning", "primary")
        )
      })
    
```

### Steps

```{r}
dtSteps <- reactive(selectHealthData(connection(), "'STEP_COUNT'" ,"'MICROSOFT_BAND'" ))

  minSt <- reactive(min(dtSteps()$x))
  maxSt <- reactive(max(dtSteps()$x))
  steps <- reactive(maxSt()-minSt())

renderValueBox({
        valueBox(
          value = tags$p(style = "font-size: 30px;",steps()),
           "Steps"
        )
      })
```


### Temperature

```{r}
dtTemp <- reactive(selectHealthData(connection(), "'SKIN_TEMPERATURE'" ,"'MICROSOFT_BAND'" ))

  temp <- reactive(mean(dtTemp()$x))

renderValueBox({
        valueBox(
          value = tags$p(style = "font-size: 30px;",(formatC(temp(),digits=3))),
          "Temperature"
        )
      })

#hr<- 5#computeHR()
#valueBox(hr, 
#         icon = "fa-heartbeat",
#         color = ifelse(hr > 170, "warning", "primary"))
```

### Speed

```{r}
dtSpeed <- reactive(selectHealthData(connection(), "'SPEED'" ,"'MICROSOFT_BAND'" ))

  speed <- reactive(mean(dtSpeed()$x))

renderValueBox({
        valueBox(
          value = tags$p(style = "font-size: 30px;",(formatC(speed(),digits=3))),
          "Speed"
        )
      })

```

### Activity

```{r}
dtMotion <- reactive(selectHealthData(connection(), "'MOTION_TYPE'" ,"'MICROSOFT_BAND'" ))

motion <- reactive(dtMotion()$x)

renderValueBox({
        valueBox(
          value = tags$p(style = "font-size: 30px;", motion()),
          "Motion"
        )
      })

```


### Drink

```{r}
#v <- 5#computeHR()
#valueBox(
#         value = tags$p(style = "font-size: 30px;",v),
#         icon = "fa-coffee")
#         color = ifelse(v > 170, "warning", "primary"))
```

### Food

```{r}
##v <- 5#computeHR()
#valueBox( 
#         value = tags$p(style = "font-size: 30px;",v),
#         icon = "fa-cutlery")
#         color = ifelse(v > 170, "warning", "primary"))
```

Row
-----------------------------------------------------------------------
