library(flexdashboard)
library(plotly)
library(dygraphs)
library(DBI)
library(mcga)
library(plyr)
library(pracma)
library(leaflet)
library(BreakoutDetection)
library(signal)
library(futile.logger)

library(data.table)
library(dplyr)


library(shiny)
library(shinydashboard)
library(shinythemes)
library(shinyjs)
library(shinyBS)

source("server/sql/selection.R")
source("server/plot/plotter.R")
source("server/math/integral.R")
source("server/math/signal.R")
source("server/util/convertation.R")
#source("server/func_settings/observe_output.R")